// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu13NxnCKg-lnh1xEJb7QC_dGKWOc9e_Q',
    appId: '1:524500760786:web:3652f484aa5fa006d3150b',
    messagingSenderId: '524500760786',
    projectId: 'aplication12-e13be',
    authDomain: 'aplication12-e13be.firebaseapp.com',
    storageBucket: 'aplication12-e13be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dImyrXB0mVBOrdj3Dcyz0ewKd5smLPU',
    appId: '1:524500760786:android:8e3313133b81c373d3150b',
    messagingSenderId: '524500760786',
    projectId: 'aplication12-e13be',
    storageBucket: 'aplication12-e13be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClEsRndHg9t0X7PRX6mBYfp8p6F3uS7mg',
    appId: '1:524500760786:ios:65b5a7fc4dbec110d3150b',
    messagingSenderId: '524500760786',
    projectId: 'aplication12-e13be',
    storageBucket: 'aplication12-e13be.firebasestorage.app',
    iosBundleId: 'com.example.application22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClEsRndHg9t0X7PRX6mBYfp8p6F3uS7mg',
    appId: '1:524500760786:ios:65b5a7fc4dbec110d3150b',
    messagingSenderId: '524500760786',
    projectId: 'aplication12-e13be',
    storageBucket: 'aplication12-e13be.firebasestorage.app',
    iosBundleId: 'com.example.application22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu13NxnCKg-lnh1xEJb7QC_dGKWOc9e_Q',
    appId: '1:524500760786:web:2f2a813609a8d474d3150b',
    messagingSenderId: '524500760786',
    projectId: 'aplication12-e13be',
    authDomain: 'aplication12-e13be.firebaseapp.com',
    storageBucket: 'aplication12-e13be.firebasestorage.app',
  );
}
